project:
  type: website

website:
  title: "spotify_rhcp"
  navbar:
    left:
      - href: README.qmd
        text: Home
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

